### ISSUE TITLE
sponsor button

### ISSUE THREAD

**Issue by publicarray** [SynoCommunity/.github#1]
@Diaoul @ymartin59 or other admins of the repositories

If you want to have the sponsor button to show up you still need to change a setting in each repository:

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository#displaying-a-sponsor-button-in-your-repository

**Comment by Diaoul** [comment]
@publicarray yes indeed, I started doing that this summer I believe and never got to finish it. I have setup a patreon and opencollective (prefered) with a few plans to show support. I think before we open that, we need to be confident about the different tiers. Any feedback would be appreciated!

**Comment by publicarray** [comment]
I don't know but I think for patreon is that there are too many options, would 3 or 4 be enough? e,g (supporter, patron, bronze)?. For opencollective supporters we can have them display in the readme:


<a href="https://opencollective.com/synocommunity/#contributors">
<img src="https://opencollective.com/synocommunity/tiers/sponsors.svg?avatarHeight=48&width=800&height=200">
</a>

<a href="https://opencollective.com/synocommunity/#contributors">
<img src="https://opencollective.com/synocommunity/tiers/backers.svg?avatarHeight=48&width=800&height=200">
</a>
